import type {ReactNode} from 'react';
import clsx from 'clsx';
import Heading from '@theme/Heading';
import styles from './styles.module.css';

type FeatureItem = {
  title: string;
  Svg: React.ComponentType<React.ComponentProps<'svg'>>;
  description: ReactNode;
};

const FeatureList: FeatureItem[] = [
  {
    title: 'Local-First',
    Svg: require('@site/static/img/undraw_docusaurus_mountain.svg').default,
    description: (
      <>
        Run entirely on your own hardware with zero external dependencies.
        Pure Rust binaries, local LLMs (Ollama/llama.cpp), and embedded data storage.
        Your data never leaves your machine.
      </>
    ),
  },
  {
    title: 'Zero-Trust Architecture',
    Svg: require('@site/static/img/undraw_docusaurus_tree.svg').default,
    description: (
      <>
        Workers execute plans deterministically with no LLM capabilities.
        Plans are generated by AGX, queued by AGQ, and executed atomically by AGW.
        Security-first design prevents unauthorized plan generation.
      </>
    ),
  },
  {
    title: 'Composable & Extensible',
    Svg: require('@site/static/img/undraw_docusaurus_react.svg').default,
    description: (
      <>
        Build Agentic Units (AUs) that follow Unix philosophy: single-purpose tools
        with stdin/stdout interfaces. Combine Unix commands with custom AUs
        to create powerful, reusable plans.
      </>
    ),
  },
];

function Feature({title, Svg, description}: FeatureItem) {
  return (
    <div className={clsx('col col--4')}>
      <div className="text--center">
        <Svg className={styles.featureSvg} role="img" />
      </div>
      <div className="text--center padding-horiz--md">
        <Heading as="h3">{title}</Heading>
        <p>{description}</p>
      </div>
    </div>
  );
}

export default function HomepageFeatures(): ReactNode {
  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row">
          {FeatureList.map((props, idx) => (
            <Feature key={idx} {...props} />
          ))}
        </div>
      </div>
    </section>
  );
}
