import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'get-started',
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/system-overview',
        'architecture/execution-layers',
        'architecture/job-schema',
        'architecture/agx-dual-model',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/security-guidelines',
        'development/testing-strategy',
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        'api/resp-protocol',
        'api/agq-endpoints',
        'api/worker-registration',
      ],
    },
    {
      type: 'category',
      label: 'Agentic Units',
      items: [
        'au-specs/agentic-unit-spec',
        'au-specs/example-au-template',
        'au-specs/testing-au',
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      link: {
        type: 'generated-index',
        title: 'Architecture Decision Records',
        description: 'Key architectural decisions for the AGEniX ecosystem',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
      ],
    },
    {
      type: 'category',
      label: 'Zero-Trust',
      items: [
        'zero-trust/zero-trust-execution',
      ],
    },
    {
      type: 'category',
      label: 'Roadmap',
      items: [
        'roadmap/roadmap-structure',
      ],
    },
  ],
};

export default sidebars;
